
// Glossary Data
const glossaryTerms = [
    {
        term: "180-Degree Rule",
        definition: "A fundamental cinematography guideline ensuring spatial consistency. It necessitates that two characters in a scene should maintain the same left/right relationship to one another, separated by an imaginary 'axis of action'."
    },
    {
        term: "ADR (Automated Dialogue Replacement)",
        matchTerm: "ADR",
        definition: "The post-production process of re-recording dialogue in a studio to replace or improve the audio captured on set (often called 'Looping').",
        image: "https://human.libretexts.org/@api/deki/files/157122/Cabin_dubbing.jpg",
        link: "https://commons.wikimedia.org/wiki/File:Cabin_dubbing.jpg"
    },
    {
        term: "Aerial Shot",
        definition: "A high-angle shot captured from an airborne device (like a drone or helicopter), often providing an expansive 'Bird's Eye View' of the setting."
    },
    {
        term: "Ambient Light",
        definition: "The pre-existing light in a shooting location, whether natural (sunlight) or artificial (street lamps), before any film lighting is added."
    },
    {
        term: "Animation",
        definition: "The art of bringing static objects or drawings to life through frame-by-frame manipulation and photography."
    },
    {
        term: "Antagonist",
        definition: "The primary force or character that stands in opposition to the protagonist's goals."
    },
    {
        term: "Artificial Light",
        definition: "Any light source generated by man-made fixtures, such as studio lamps or LEDs, as opposed to natural sources."
    },
    {
        term: "Aspect Ratio",
        definition: "The specific relationship between the width and height of the film frame (e.g., 16:9 for widescreen, 4:3 for television).",
        image: "https://human.libretexts.org/@api/deki/files/157124/1024px-Aspect_ratios_for_film.png",
        link: "https://commons.wikimedia.org/wiki/File:Aspect_ratios_for_film.png"
    },
    {
        term: "Assistant Director",
        definition: "The logistical backbone of the set, responsible for managing the daily schedule, coordinating the crew, and ensuring the production stays on time."
    },
    {
        term: "Asynchronism",
        definition: "A creative mismatch between image and sound where they do not operate in unison, often used for metaphorical or contrapuntal effect."
    },
    {
        term: "Auteur Theory",
        definition: "A critical framework suggesting the director is the primary 'author' of a film, imbuing it with a distinct personal style and vision."
    },
    {
        term: "Axis of Action",
        definition: "The invisible boundary line that dictates spatial continuity in a scene; crossing it reverses the relative positions of the characters."
    },
    {
        term: "Backlight",
        definition: "A light positioned behind the subject, used to create a glowing rim or separate them from the background."
    },
    {
        term: "Barn Doors",
        definition: "Adjustable metal flaps on lighting fixtures used to shape and direct the beam of light."
    },
    {
        term: "Best Boy",
        definition: "The second-in-command to the Gaffer or Key Grip, handling equipment inventory, personnel management, and electrical logistics."
    },
    {
        term: "Blocking",
        definition: "The choreographed physical movement and positioning of actors within the frame during a scene."
    },
    {
        term: "Boom Shot",
        definition: "A fluid shot created by a camera mounted on a counterweighted boom arm or jib that allows for vertical and horizontal movement."
    },
    {
        term: "Bridging Shot",
        definition: "A transitional shot used to bridge a gap in time or space, such as falling calendar pages or a clock ticking."
    },
    {
        term: "Call Sheet",
        definition: "The daily production schedule distributed to cast and crew, detailing call times, scenes to be filmed, and locations."
    },
    {
        term: "CGI",
        definition: "Computer Generated Imagery: Visual elements created digitally to enhance, extend, or replace live-action footage."
    },
    {
        term: "Character",
        definition: "A fictional persona constructed through performance, dialogue, and action to drive the narrative."
    },
    {
        term: "Chiaroscuro Lighting",
        definition: "A high-contrast lighting style emphasizing shadows and light, often used to create drama or volume (borrowed from Renaissance painting)."
    },
    {
        term: "Cinema Verité",
        definition: "A style of documentary filmmaking ('cinema truth') that favors immediacy, handheld camerawork, and raw reality over polished production."
    },
    {
        term: "Cinematographer",
        definition: "The Director of Photography (DP) who orchestrates the visual translation of the script through lighting, lens choice, and composition."
    },
    {
        term: "Cinematic Language",
        definition: "The visual and auditory vocabulary (cuts, angles, sound) filmmakers use to communicate meaning to the audience."
    },
    {
        term: "Classical Acting",
        definition: "A traditional performance style rooted in theatrical training, emphasizing vocal precision, physical control, and analysis."
    },
    {
        term: "Classical Editing",
        definition: "'Invisible' editing that prioritizes a seamless narrative flow, ensuring the mechanism of the cut goes unnoticed by the viewer."
    },
    {
        term: "Climax",
        definition: "The narrative peak where the conflict reaches its highest tension and is decisively resolved."
    },
    {
        term: "Close-up",
        matchTerm: "Close-up",
        definition: "A tight shot framing a subject—usually the face—to emphasize detail, expression, and emotional intimacy."
    },
    {
        term: "Color Temperature",
        definition: "The quantitative measure of a light source's color spectrum, ranging from warm (amber/red) to cool (blue)."
    },
    {
        term: "Composition",
        definition: "The artistic arrangement of visual elements within the frame to guide the viewer's eye."
    },
    {
        term: "Continuity Editing",
        definition: "The standard system of editing that maintains continuous and clear narrative action across cuts."
    },
    {
        term: "Coverage",
        definition: "The variety of shots (angles, focal lengths) captured for a single scene to provide options during editing."
    },
    {
        term: "Craft Services",
        definition: "The on-set department responsible for providing food, drinks, and snacks to keep the cast and crew fueled."
    },
    {
        term: "Crane Shot",
        definition: "A sweeping shot achieved by mounting the camera on a crane, allowing for dramatic vertical and horizontal movement through space."
    },
    {
        term: "Cross-Cutting",
        definition: "A technique cutting between two or more independent storylines occurring simultaneously (often called Parallel Editing)."
    },
    {
        term: "Cross-Fade",
        definition: "An audio transition where one sound gradually fades out as another fades in, creating a smooth overlap."
    },
    {
        term: "C-Stand",
        definition: "A heavy-duty metal stand used to support lighting modifiers, flags, and other grip equipment (Century Stand)."
    },
    {
        term: "Cut",
        definition: "The foundational transition in editing; an instantaneous switch from one shot to another."
    },
    {
        term: "Cut-Away",
        definition: "A brief shot that interrupts the main action to show a related detail or reaction, often used to mask edits."
    },
    {
        term: "Cutting on Action",
        definition: "An editing technique where a cut is placed in the middle of a movement to make the transition appear seamless."
    },
    {
        term: "Dailies",
        definition: "The raw, unedited footage shot during a production day, viewed by the director and key crew to ensure quality."
    },
    {
        term: "Day-for-Night",
        definition: "A technique of shooting in daylight but manipulating exposure and filters to simulate the look of night."
    },
    {
        term: "Denouement",
        definition: "The final resolution of the story following the climax, where loose ends are tied up."
    },
    {
        term: "Depth of Field",
        definition: "The zone of acceptable sharpness in front of and behind the subject in focus."
    },
    {
        term: "Diegetic",
        definition: "Any sound or element that originates from within the film's narrative world (e.g., a radio playing in a scene)."
    },
    {
        term: "Direct Cinema",
        definition: "An observational documentary genre where the filmmaker acts as a detached 'fly on the wall', avoiding interference."
    },
    {
        term: "Direct Sound",
        definition: "Audio recorded live on location during the take, preserving the natural ambiance and performance."
    },
    {
        term: "Director",
        definition: "The artistic captain of the film, guiding the creative vision and harmonizing the contributions of cast and crew."
    },
    {
        term: "Dissolves",
        definition: "A gradual transition where one image fades into another, briefly superimposing them."
    },
    {
        term: "Dolly Shot",
        definition: "A smooth, moving shot where the camera travels on a wheeled platform (dolly), often on tracks."
    },
    {
        term: "Dutch Angle",
        definition: "A shot where the horizon line is intentionally tilted, creating a sense of disorientation or unease."
    },
    {
        term: "Editing",
        definition: "The art of assembling shots into a coherent sequence to craft the narrative, pacing, and tone."
    },
    {
        term: "Ellipsis",
        definition: "An editing device that omits a period of time, allowing the narrative to jump forward cleanly."
    },
    {
        term: "Establishing Shot",
        definition: "A wide shot, typically at the start of a scene, that sets the location and spatial relationships."
    },
    {
        term: "Explicit Meaning",
        definition: "The clear, surface-level information or moral presented directly by the film."
    },
    {
        term: "Exposure",
        definition: "The amount of light allowed to strike the camera sensor or film, determining the brightness of the image."
    },
    {
        term: "Extreme Close-Up",
        definition: "A very tight shot that magnifies a small detail, such as an eye or a trigger."
    },
    {
        term: "Eye Level Shot",
        definition: "A neutral camera angle placed at the subject's eye height, simulating a natural human gaze."
    },
    {
        term: "Fade-in",
        definition: "A transition where the screen brightens from black (or white) to a full image."
    },
    {
        term: "Fade-out",
        definition: "A transition where the image gradually darkens until the screen is black."
    },
    {
        term: "Fast Film Stock",
        definition: "Highly light-sensitive film stock suitable for low-light conditions, often with more visible grain."
    },
    {
        term: "Fast Motion",
        definition: "A visual effect where action accelerates, achieved by filming at a slower frame rate than playback."
    },
    {
        term: "Fill Light",
        definition: "A secondary light source used to soften the shadows created by the key light."
    },
    {
        term: "Film Gauge",
        definition: "The physical width of the film strip, such as 35mm, 16mm, or 8mm."
    },
    {
        term: "Film Stock",
        definition: "The analog medium used for recording motion pictures, consisting of light-sensitive emulsion on a base."
    },
    {
        term: "Flashback",
        definition: "A narrative device that interrupts the chronological flow to show an event from the past."
    },
    {
        term: "Flashforward",
        definition: "A narrative jump that glimpses a future event."
    },
    {
        term: "Flat Lighting",
        definition: "Low-contrast lighting that illuminates a scene evenly, minimizing shadows and depth."
    },
    {
        term: "Focus Puller",
        definition: "The 1st Assistant Camera (AC) responsible for maintaining sharp focus on the subject as they move."
    },
    {
        term: "Foley Artists",
        definition: "Sound specialists who perform and record custom sound effects (footsteps, cloth rustle) in sync with the picture."
    },
    {
        term: "Foley Sounds",
        definition: "Everyday sound effects recreated in a studio to replace or enhance the original production audio."
    },
    {
        term: "Fourth Wall",
        definition: "The imaginary barrier separating the fictional world of the characters from the real world of the audience."
    },
    {
        term: "Frame",
        definition: "The single rectangular image that forms the building block of cinema, or the physical boundaries of the image."
    },
    {
        term: "Frame Rate",
        definition: "The frequency at which frames are displayed (e.g., 24fps for standard cinema)."
    },
    {
        term: "Framing",
        definition: "The decision of what to include within the borders of the image and how to position it."
    },
    {
        term: "Freeze Frame",
        definition: "A visual effect where the action freezes, achieved by repeating a single frame."
    },
    {
        term: "Gaffer",
        definition: "The chief lighting technician responsible for executing the cinematographer's lighting plan."
    },
    {
        term: "Gate",
        definition: "The aperture in a camera or projector where the film is momentarily held stationary for exposure."
    },
    {
        term: "Genre",
        definition: "A category of film (e.g., Western, Sci-Fi) defined by shared codes, conventions, and styles."
    },
    {
        term: "Greenlight",
        definition: "The official studio approval that allows a project to move from development into production."
    },
    {
        term: "Grip",
        definition: "The technician responsible for camera support (dollies, cranes) and lighting rigging."
    },
    {
        term: "Handheld Shot",
        definition: "A shot captured with the camera resting on the operator's shoulder or hands, creating a raw, shaky aesthetic."
    },
    {
        term: "High-Angle Shot",
        definition: "A shot looking down on the subject, often making them appear diminished or vulnerable."
    },
    {
        term: "High-Key Lighting",
        definition: "A bright lighting style with low contrast and few shadows, often used in comedies."
    },
    {
        term: "Hitting a Mark",
        definition: "The actor's act of moving to a precise, pre-determined spot on the floor during a take."
    },
    {
        term: "Implicit Meaning",
        definition: "The subtle, underlying significance or association in a film, requiring viewer interpretation."
    },
    {
        term: "Insert Shot",
        definition: "A close-up shot of a detail (like a watch or a letter) inserted into a scene to verify a plot point."
    },
    {
        term: "Intellectual Montage",
        definition: "An editing technique (pioneered by Eisenstein) colliding contrasting images to generate a new abstract idea."
    },
    {
        term: "Iris",
        definition: "A classic transition where a circular mask closes down to end a scene (Iris-Out) or opens to begin one (Iris-In)."
    },
    {
        term: "J-Cut",
        definition: "An audio bridge where the sound of the next scene acts as a pre-echo before the visuals cut."
    },
    {
        term: "Jump Cut",
        definition: "A jarring, elliptical cut that breaks temporal continuity by skipping a small portion of time within the same shot."
    },
    {
        term: "Key Light",
        definition: "The primary light source illuminating the subject, establishing the dominance of light and shadow."
    },
    {
        term: "Keying",
        definition: "The process of isolating a specific color (like greenscreen) to make it transparent for compositing."
    },
    {
        term: "Kuleshov Effect",
        definition: "A cognitive phenomenon where the audience derives more meaning from the interaction of two shots than from a single shot in isolation."
    },
    {
        term: "Last Looks",
        definition: "The final call for hair, makeup, and wardrobe touches before the camera rolls."
    },
    {
        term: "Lavalier",
        matchTerm: "Lav Mic",
        definition: "A discreet, small microphone often clipped to an actor's clothing."
    },
    {
        term: "L-Cut",
        definition: "An audio transition where the sound from the current scene carries over into the beginning of the next scene."
    },
    {
        term: "Leitmotif",
        definition: "A recurring musical theme explicitly associated with a particular character, idea, or situation."
    },
    {
        term: "Lens",
        definition: "The optical glass assembly that focuses light rays onto the recording medium."
    },
    {
        term: "Letterboxing",
        definition: "The practice of transferring wide-screen film to standard-width video formats while preserving the original aspect ratio, resulting in black bars."
    },
    {
        term: "Lighting",
        definition: "The creative control of light to establish mood, depth, and time of day."
    },
    {
        term: "Line Producer",
        definition: "The producer managing the daily operations, budget, and physical needs of the production."
    },
    {
        term: "Lip Sync",
        definition: "The technical synchronization of spoken dialogue with the visual movement of the speaker's lips."
    },
    {
        term: "Location",
        definition: "A real-world environment used for filming, distinct from a constructed studio set."
    },
    {
        term: "Logline",
        definition: "A concise, one-sentence summary of the film's central conflict and hook."
    },
    {
        term: "Long Shot",
        definition: "A shot where the human figure appears small in the frame, dominated by the surrounding environment."
    },
    {
        term: "Long Take",
        definition: "An extended, uninterrupted shot that allows a scene to unfold in real time."
    },
    {
        term: "Looping",
        definition: "The process of re-recording dialogue lines in a studio (see ADR)."
    },
    {
        term: "Low-Angle Shot",
        definition: "A shot looking up at the subject, often imbuing them with power or dominance."
    },
    {
        term: "Low-Key Lighting",
        definition: "A lighting style marked by high contrast and deep shadows, typical of Film Noir."
    },
    {
        term: "MacGuffin",
        definition: "A plot device that drives the characters' actions and the story forward, though its specific nature may be unimportant (e.g., the briefcase in Pulp Fiction)."
    },
    {
        term: "Magic Hour",
        definition: "The brief window of soft, warm, diffuse light just after sunset or before sunrise."
    },
    {
        term: "Master Shot",
        definition: "A single, continuous wide shot that records the entire action of a scene, serving as a safety reference."
    },
    {
        term: "Match Cut",
        definition: "A cut that preserves continuity between two shots by matching action, composition, or audio."
    },
    {
        term: "Matte",
        definition: "A mask used to block out a portion of the frame to allow for the insertion of another image (compositing)."
    },
    {
        term: "Medium Shot",
        definition: "A standard shot framing the subject from the waist up, capturing both gesture and expression."
    },
    {
        term: "Method Acting",
        definition: "An immersive acting technique where the performer draws on personal emotional memory to inhabit the character."
    },
    {
        term: "Mise-en-scène",
        definition: "The total visual orchestration of everything that appears before the camera—sets, props, lighting, and actors."
    },
    {
        term: "Montage",
        definition: "A sequence of short shots edited together to condense time, space, or info, or to create symbolic meaning."
    },
    {
        term: "Motifs",
        definition: "Recurring thematic elements—visual, auditory, or narrative—that reinforce the film's core ideas."
    },
    {
        term: "Narration",
        definition: "The act of telling the story, often through a voice-over commentary."
    },
    {
        term: "Narrative Structure",
        definition: "The organizational framework (e.g., three-act structure) that shapes how the story unfolds."
    },
    {
        term: "Natural Light",
        definition: "Light derived from non-artificial sources like the sun, moon, or fire."
    },
    {
        term: "Naturalistic Acting",
        definition: "A performance style that aims for verisimilitude and the appearance of unforced, real-life behavior."
    },
    {
        term: "Non-Diegetic",
        definition: "Elements (like the musical score or subtitles) that exist outside the character's world."
    },
    {
        term: "Off-Screen Dialogue",
        definition: "Speech from a character who is part of the scene but is currently outside the camera frame."
    },
    {
        term: "Over-the-Shoulder",
        definition: "A shot filmed from behind the shoulder of one character, famously establishing a conversation connection."
    },
    {
        term: "Pan",
        definition: "A horizontal scanning movement of the camera from a fixed pivot point."
    },
    {
        term: "Parallel Editing",
        definition: "Cutting between two concurrent storylines to build tension or draw comparisons (Cross-Cutting)."
    },
    {
        term: "Pick-ups",
        definition: "Minor shots or small portions of scenes recorded after principal photography to correct errors or fill gaps."
    },
    {
        term: "POV (Point of View)",
        matchTerm: "POV",
        definition: "A subjective shot that replicates exactly what a character sees."
    },
    {
        term: "Practical Light",
        definition: "Working light sources visible within the scene, such as desk lamps or car headlights."
    },
    {
        term: "Prime Lens",
        definition: "A lens with a fixed focal length, prized for optical quality and wider apertures."
    },
    {
        term: "Producer",
        definition: "The executive who initiates, coordinates, supervises, and controls all aspects of the motion picture production."
    },
    {
        term: "Production Designer",
        definition: "The artist responsible for the overall visual aesthetic of the film's environments."
    },
    {
        term: "Props",
        definition: "Portable objects handled by actors to advance the action."
    },
    {
        term: "Protagonist",
        definition: "The central character who drives the narrative and with whom the audience is often asked to empathize."
    },
    {
        term: "Rack Focus",
        definition: "The act of shifting the plane of critical focus during a shot to direct the viewer's attention."
    },
    {
        term: "Reaction Shot",
        definition: "A cut-away to a character's face to show their emotional response to the preceding action."
    },
    {
        term: "Real Time",
        definition: "A narrative mode where the screen duration of events exactly matches their actual duration."
    },
    {
        term: "Rear Projection",
        definition: "An older visual effects technique where background scenery is projected onto a screen behind the actors."
    },
    {
        term: "Reflexivity",
        definition: "When a film self-consciously calls attention to its own status as a constructed work of art."
    },
    {
        term: "Resolution",
        definition: "The clarity and detail of an image, often measured in pixels."
    },
    {
        term: "Reverse Motion",
        definition: "A visual effect where the action is played backward."
    },
    {
        term: "Rule of Thirds",
        definition: "A compositional guideline dividing the frame into a 3x3 grid, placing key elements along the lines or intersections."
    },
    {
        term: "Score",
        definition: "The original instrumental music composed specifically to accompany the film."
    },
    {
        term: "Screen Direction",
        definition: "The consistent direction of movement across the screen, crucial for maintaining spatial logic."
    },
    {
        term: "Screen Time",
        definition: "The duration an event takes to unfold on screen, which can be expanded or compressed relative to real time."
    },
    {
        term: "Screenplay",
        definition: "The written blueprint of the film, containing dialogue, action instructions, and scene settings."
    },
    {
        term: "Seiyū",
        definition: "The Japanese term used to designate a voice actor, distinct in its cultural celebrity status."
    },
    {
        term: "Sequence Shot",
        definition: "A complex long take that captures an entire narrative sequence without edits."
    },
    {
        term: "Set",
        definition: "The constructed environment or location where filming takes place."
    },
    {
        term: "Set Design",
        definition: "The creation and decoration of the physical scenery."
    },
    {
        term: "Set Lights",
        definition: "The various lighting instruments used to illuminate the set."
    },
    {
        term: "Setting",
        definition: "The time and place in which the film's story occurs."
    },
    {
        term: "Shot",
        definition: "The basic unit of film structure; a continuous, unedited piece of exposed film."
    },
    {
        term: "Shot List",
        definition: "The director's itemized document detailing every shot needed for the day's filming."
    },
    {
        term: "Showrunner",
        definition: "The executive producer who holds creative authority and management over a television series."
    },
    {
        term: "Sides",
        definition: "Excerpts from the script containing only the scenes to be shot that day or used for auditions."
    },
    {
        term: "Slate",
        definition: "The clapperboard used at the start of a take to mark the scene number and sync audio."
    },
    {
        term: "Slow Film Stock",
        definition: "Low-sensitivity film requiring more light but producing a finer grain image."
    },
    {
        term: "Slow Motion",
        definition: "The effect of time decelerating, achieved by recording at a higher frame rate than the playback speed."
    },
    {
        term: "Sound Bridge",
        definition: "A transition where audio from one scene leads into or overlaps with the next scene."
    },
    {
        term: "Sound Design",
        definition: "The planning and creation of the film's complete aural environment."
    },
    {
        term: "Sound Mixer",
        definition: "The production crew member responsible for recording balanced, clean audio on set."
    },
    {
        term: "Sound Stage",
        definition: "A large, soundproofed hangar-like structure used for film production."
    },
    {
        term: "Soviet Montage",
        definition: "A film theory suggesting meaning is derived from the collision of shots rather than their continuity."
    },
    {
        term: "Special Effects (SFX)",
        definition: "Practical illusions created physically on set (explosions, prosthetics), as opposed to digital effects."
    },
    {
        term: "Steadicam",
        definition: "A camera stabilizing mount that isolates the camera from the operator's movement for smooth shots."
    },
    {
        term: "Stock Footage",
        definition: "Existing film material (newsreels, landscapes) reused in a new production."
    },
    {
        term: "Stop Motion",
        definition: "An animation technique where physical objects are moved in small increments between individually photographed frames."
    },
    {
        term: "Storyboard",
        definition: "A sequence of drawings representing the shots planned for a production."
    },
    {
        term: "Style",
        definition: "The distinctive manner in which a filmmaker utilizes cinematic techniques."
    },
    {
        term: "Subtext",
        definition: "The unspoken thoughts, motives, and meanings beneath the dialogue."
    },
    {
        term: "Superimposition",
        definition: "The placement of one image over another, allowing both to be seen simultaneously."
    },
    {
        term: "Sync",
        definition: "The precise temporal alignment of sound and image."
    },
    {
        term: "Telephoto Lens",
        definition: "A long lens that magnifies distant objects, compressing the perception of depth."
    },
    {
        term: "Theme",
        definition: "The central or dominant idea explored throughout the film."
    },
    {
        term: "Theory",
        definition: "The academic study and philosophical models attempting to explain the nature of cinema."
    },
    {
        term: "Three-Point Lighting",
        definition: "The standard lighting setup consisting of a key light, fill light, and backlight."
    },
    {
        term: "Tilt",
        definition: "A vertical camera movement where the camera pivots up or down from a stationary axis."
    },
    {
        term: "Time Lapse",
        definition: "A technique where slow events (like a blooming flower) are played back at high speed."
    },
    {
        term: "Tracking Shot",
        definition: "A shot that follows a subject's movement through space, often moving alongside them."
    },
    {
        term: "Transitions",
        definition: "The methods used to join two shots together (e.g., cut, fade, dissolve)."
    },
    {
        term: "Treatment",
        definition: "A prose narrative summary of a film, used to pitch the story before a script is written."
    },
    {
        term: "Two Shot",
        definition: "A medium shot framing two characters, typically interacting."
    },
    {
        term: "Video Village",
        definition: "The technical hub on set where monitors allow the director and clients to review the live feed."
    },
    {
        term: "Visual Effects (VFX)",
        definition: "Imagery generated, manipulated, or enhanced outside of the live-action shooting context (e.g., in a computer)."
    },
    {
        term: "Visual Lexicon",
        definition: "The vocabulary of visual symbols and techniques a filmmaker uses to tell a story."
    },
    {
        term: "Voice Over",
        definition: "Spoken narration or dialogue recorded by a character not currently visible on screen."
    },
    {
        term: "White Balance",
        definition: "The camera adjustment that ensures white objects appear white, neutralizing different color temperatures."
    },
    {
        term: "Whip Pan",
        matchTerm: "Swish Pan",
        definition: "A pan executed so rapidly that the image blurs into indistinguishable streaks."
    },
    {
        term: "Wide Angle Lens",
        definition: "A short lens with a broad field of view, expanding the sense of depth and space."
    },
    {
        term: "Wide Shot",
        definition: "A shot that emphasizes the environment and the subject's placement within it."
    },
    {
        term: "Wipe",
        definition: "A transition where a line passes across the screen, pushing one shot off to reveal the next."
    },
    {
        term: "Zoom Lens",
        definition: "A lens with a variable focal length, allowing the operator to change magnification."
    },
    {
        term: "Zoom Shot",
        definition: "The act of changing the lens's focal length during a shot to appear to move closer to or further from the subject."
    }
];

// Logic to process glossary
document.addEventListener('DOMContentLoaded', () => {
    // Sort terms by length (longest first) to prevent partial matching issues
    const sortedTerms = glossaryTerms.sort((a, b) => (b.matchTerm || b.term).length - (a.matchTerm || a.term).length);

    // Create Tooltip Element
    const tooltip = document.createElement('div');
    tooltip.className = 'glossary-tooltip';
    document.body.appendChild(tooltip);

    // Target content areas (exclude nav, footer, etc.)
    const contentAreas = document.querySelectorAll('.textbook-content, .hero-content p, .intro-main p, .card p');

    contentAreas.forEach(area => {
        processNode(area, sortedTerms);
    });

    // Tooltip Logic
    let currentTooltipTerm = null;
    let tooltipVisible = false;

    function showTooltip(term, e) {
        const termKey = term.getAttribute('data-term');
        const data = glossaryTerms.find(t => (t.matchTerm || t.term) === termKey);

        if (data) {
            let content = `<strong>${data.term}</strong><br>${data.definition}`;
            if (data.image) {
                content += `<br><img src="${data.image}" alt="${data.term}" style="max-width:100%; margin-top:10px; border-radius:4px;">`;
            }
            if (data.caption) {
                content += `<br><small>${data.caption}</small>`;
            }
            tooltip.innerHTML = content;
            tooltip.style.display = 'block';
            tooltipVisible = true;
            currentTooltipTerm = term;

            // Positioning
            const rect = term.getBoundingClientRect();
            let top = rect.bottom + window.scrollY + 5;
            let left = rect.left + window.scrollX;

            // Adjust if off screen
            if (left + 300 > window.innerWidth) {
                left = window.innerWidth - 310;
            }
            if (left < 10) {
                left = 10;
            }

            tooltip.style.top = `${top}px`;
            tooltip.style.left = `${left}px`;
        }
    }

    function hideTooltip() {
        tooltip.style.display = 'none';
        tooltipVisible = false;
        currentTooltipTerm = null;
    }

    document.querySelectorAll('.glossary-term').forEach(term => {
        // Desktop hover
        term.addEventListener('mouseenter', (e) => {
            showTooltip(e.target, e);
        });

        term.addEventListener('mouseleave', () => {
            hideTooltip();
        });

        // Mobile touch/click support
        term.addEventListener('click', (e) => {
            e.preventDefault();
            e.stopPropagation();
            if (tooltipVisible && currentTooltipTerm === e.target) {
                hideTooltip();
            } else {
                showTooltip(e.target, e);
            }
        });
    });

    // Close tooltip when tapping elsewhere on mobile
    document.addEventListener('click', (e) => {
        if (tooltipVisible && !e.target.classList.contains('glossary-term') && !tooltip.contains(e.target)) {
            hideTooltip();
        }
    });
});

function processNode(node, terms) {
    // Process text nodes only
    if (node.nodeType === 3) {
        let content = node.nodeValue;
        let originalContent = content;
        let replaced = false;

        // Skip if inside specific tags (links, already processed, headers)
        if (node.parentNode.tagName === 'A' ||
            node.parentNode.tagName === 'H1' ||
            node.parentNode.tagName === 'H2' ||
            node.parentNode.tagName === 'H3' ||
            node.parentNode.classList.contains('glossary-term')) {
            return;
        }

        terms.forEach(termData => {
            if (replaced) return; // Simple avoidance of double-wrapping for now

            const term = termData.matchTerm || termData.term;
            // distinct regex to avoid replacing parts of words
            const regex = new RegExp(`\\b(${escapeRegExp(term)})\\b`, 'i');

            if (regex.test(content)) {
                // Split logic to preserve DOM structure would be complex, 
                // so we use a simpler replacement wrapper strategy for this iteration
                // Note: This replaces the *first* instance found in this text node for simplicity and performance
                const match = content.match(regex);
                if (match) {
                    // Create wrapper
                    const span = document.createElement('span');
                    span.className = 'glossary-term';
                    span.setAttribute('data-term', term);
                    span.textContent = match[0]; // Use original casing

                    // Split text node
                    const index = match.index;
                    const before = content.slice(0, index);
                    const after = content.slice(index + match[0].length);

                    const afterNode = document.createTextNode(after);
                    const beforeNode = document.createTextNode(before);

                    // Modify DOM
                    node.parentNode.insertBefore(beforeNode, node);
                    node.parentNode.insertBefore(span, node);
                    node.parentNode.insertBefore(afterNode, node);
                    node.parentNode.removeChild(node);

                    replaced = true;

                    // Recursively process the rest (afterNode) to catch multiple terms in one block
                    processNode(afterNode, terms);
                }
            }
        });
    } else if (node.nodeType === 1 && !['SCRIPT', 'STYLE', 'IMG', 'IFRAME'].includes(node.tagName)) {
        // Recurse into children
        Array.from(node.childNodes).forEach(child => processNode(child, terms));
    }
}

function escapeRegExp(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
